SELECT
  *
FROM dbo.CTDATHANG
INNER JOIN dbo.DONDATHANG
  ON CTDATHANG.SoDH = DONDATHANG.SoDH
INNER JOIN dbo.NHACUNGCAP
  ON DONDATHANG.MaNCC = NHACUNGCAP.MaNCC
INNER JOIN dbo.VATTU
  ON CTDATHANG.MaVT = VATTU.MaVT
INNER JOIN dbo.CTPHIEUNHAP
  ON CTPHIEUNHAP.MaVT = VATTU.MaVT
INNER JOIN dbo.CTPHIEUXUAT
  ON CTPHIEUXUAT.MaVT = VATTU.MaVT
INNER JOIN dbo.PHIEUXUAT
  ON CTPHIEUXUAT.SoPX = PHIEUXUAT.SoPX
INNER JOIN dbo.TONKHO
  ON TONKHO.MaVT = VATTU.MaVT
INNER JOIN dbo.PHIEUNHAP
  ON PHIEUNHAP.SoDH = DONDATHANG.SoDH
    AND CTPHIEUNHAP.SoPN = PHIEUNHAP.SoPN
